version: '3.8'

networks:
  spark-network:

x-defaults:
  &spark-common
  image: apache-spark
  user: root
  networks:
    - spark-network
  volumes:
    - .:/opt/ufo-deltalake
    - ./logs/spark:/opt/bitnami/spark/logs
    - ./src/spark/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf

services:
  spark-master:
    <<: *spark-common
    container_name: spark-master
    hostname: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
    ports:
      - 8080:8080
      - 7077:7077

  spark-worker-1:
    <<: *spark-common
    container_name: spark-worker-1
    hostname: spark-worker-1
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
    ports:
      - 4040:4040

  spark-worker-2:
    <<: *spark-common
    container_name: spark-worker-2
    hostname: spark-worker-2
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
    ports:
      - 4041:4041

  spark-history-server:
    <<: *spark-common
    container_name: spark-history-server
    hostname: spark-history-server
    depends_on:
      - spark-master
    environment:
      - SPARK_HISTORY_OPTS=-Dspark.history.fs.logDirectory=file:/opt/bitnami/spark/logs
    ports:
      - 18080:18080
    command: >
      bash -c "/opt/bitnami/spark/sbin/start-history-server.sh"

  spark-driver:
    image: ufo-deltalake
    container_name: spark-driver
    hostname: spark-driver
    tty: true
    depends_on:
      - spark-master 
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - spark-network
    ports:
      - 8888:8888
    volumes:
      - .:/opt/ufo-deltalake